image: "rust:latest"

stages:
  - build
  - test

before_script:
  # install dependencies
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential
  - apt-get install -yqq check libssl-dev imagemagick-common
  # generate test data
  - ./gen_test_img.sh
  - ./cp_test_files.sh

# /mangofmt
mangofmt-build:
  stage: build
  script:
    - rustc --version && cargo --version      # Print version info for debugging
    - cd mangofmt
    - cargo build

mangofmt-test:
    stage: test
    script:
      - rustc --version && cargo --version      # Print version info for debugging
      - cd mangofmt
      - cargo test --all --verbose

# /libmango
libmango-build:
    stage: build

    script:
      - cd libmango
      - make build
    
libmango-build:
    stage: test

    script:
      - cd libmango
      - echo "compile test"
      - make test/run_tests
      - echo "run tests"
      - make test
 
