[package]
name = "libmango"
version = "0.1.0"
authors = ["Alex Fence <alexfence.code@gmail.com>"]

[features]
aes = ["mangofmt/aes"]
gzip = ["mangofmt/gzip"]

[dependencies]
mangofmt = { path = "../mangofmt"}

[lib]
name = "mango"
crate-type = ["cdylib"]
